name: update

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  monthly:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib openpyxl xlrd
    - name: Run Jupyter Notebook
      run: jupyter nbconvert --to notebook --execute "taiwan-us-trade.ipynb" --stdout
    - name: Display CSV content
      run: cat taiwan-us-trade.csv
    - name: Update file timestamp
      run: touch taiwan-us-trade.csv
    - name: Force add CSV
      run: git add -f taiwan-us-trade.csv
    - name: Commit and push changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Update data $(date -u)" || echo "No changes to commit"
        git push
