name: update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib openpyxl xlrd urljoin os

    - name: Scrape data and run notebook
      run: jupyter nbconvert --to notebook --execute "test.ipynb" --stdout

    - name: Check if CSV is generated
      run: ls -l  # List files to verify CSV creation

    - name: Check git status
      run: git status  # Check if CSV is tracked

    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -f taiwan-us-trade.csv  # Force-add the CSV file
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
